version: '3.0'
  
services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM='Registry Realm'
    volumes:
      - /home/kmserver/Registry/registry-config.yml:/etc/docker/registry/config.yml
      - /home/kmserver/Registry/registry:/var/lib/registry
      - /home/kmserver/Registry/auth:/auth
